### ISSUE TITLE
Support custom max heart rate outside of standard fomulas

### ISSUE THREAD

**Issue by ericbisme** [werkkrew/ciq-orange-theory#9]
Now that Orange Theory supports updating your heart rate to a measured max after 20 classes this app can get our of sync with the zones being used in studio. It would be helpful to have a third heart rate option to allow a custom number. Thanks!

**Comment by supersmo** [comment]
I noticed that I could consistently get my heart rate above 100% when pushing myself and found this reported issue.
I made a pull request where I added an option to use the Max HR from the user profile instead of using the formulas and tested it in the emulator (Garmin Vivoactive HR) and also on my Forerunner 245 Music watch.

Great app by the way!
